### ISSUE TITLE
Please specify a bucket name for the client in s-project.json - pg 93 on deploy

### ISSUE THREAD

**Issue by bartonhammond** [JustServerless/learnserverless-book#9]
My `notes/s-project.json` is exactly the same as GIT repo:

```
{
  "name": "notes",
  "custom": {},
  "plugins": [
    "serverless-client-s3"
  ]
}
```

Log:

```
~/projects/Serverless/notes (master)$ serverless
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.6
`-------'

Commands
* Serverless documentation: http://docs.serverless.com
* You can run commands with "serverless" or the shortcut "sls"
* Pass "--help" after any <context> <action> for contextual help
* Add "--debug" to any command for extra useful logs

project ........ create, init, install, remove
function ....... create, deploy, logs, remove, rollback, run
endpoint ....... deploy, remove
event .......... deploy, remove
dash ........... deploy, summary
stage .......... create, remove
region ......... create, remove
resources ...... deploy, diff, remove
plugin ......... create
variables ...... list, set, unset
client ......... deploy

~/projects/Serverless/notes (master)$ serverless client deploy
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: Please specify a bucket name for the client in s-project.json
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at ClientDeploy._validateAndPrepare (/Users/barton/projects/Serverless/notes/node_modules/serverless-client-s3/index.js:112:33)
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:190:17)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
~/projects/Serverless/notes (master)$ 
```

**Comment by bartonhammond** [comment]
Found docs: [https://github.com/serverless/serverless-client-s3](https://github.com/serverless/serverless-client-s3) which require bucket name

Changed to:

```
{
  "name": "notes",
  "custom" : {
    "client": {
        "bucketName": "notes.${stage}.${region}"
    }
  },
  "plugins": [
    "serverless-client-s3"
  ]
}
```

**Comment by bartonhammond** [comment]
Verified that S3 bucket was created:

<img width="1354" alt="screen shot 2016-06-21 at 6 30 10 pm" src="https://cloud.githubusercontent.com/assets/1282364/16249822/4de98aa4-37de-11e6-86af-009476618799.png">

**Comment by pmuens** [comment]
👍 Thank you for pointing that out. Seems like this is a new mandatory setting (thank you for the PR as well!).
